import Link from 'next/link'

export default function AnimalRehabilitationContent() {
  return (
    <>
        <h2 className="text-2xl font-bold mt-10 mb-4" data-aos="fade-up">What Is Animal Rehabilitation?</h2>
        <p className="leading-relaxed mb-4" data-aos="fade-up"><strong>Animal rehabilitation</strong> is the use of evidence-based physical therapies to restore movement, reduce pain, and improve function in dogs, cats, and other companion animals. It is the veterinary equivalent of human physical therapy and physiotherapy — applying the same scientific principles, adapted for four-legged patients.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">At RehabVet, animal rehabilitation encompasses a comprehensive range of modalities: <Link href="/services/hydrotherapy-for-dogs" className="text-primary hover:underline">hydrotherapy</Link> (underwater treadmill), <Link href="/services/dog-physiotherapy-singapore" className="text-primary hover:underline">physiotherapy</Link> (manual therapy and therapeutic exercises), acupuncture, Class 4 laser therapy, electrotherapy (TENS &amp; NMES), therapeutic ultrasound, shockwave therapy, and hyperbaric oxygen therapy.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Unlike human medicine, where rehabilitation after surgery or injury is standard practice, veterinary rehabilitation is still a relatively young field in Singapore. RehabVet was established as <strong>Singapore’s first dedicated animal rehabilitation clinic</strong> — and remains the most comprehensive facility of its kind, with purpose-built equipment, qualified rehabilitation therapists, and full veterinary oversight for every session.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">The effectiveness of veterinary rehabilitation is well-supported by clinical research. Studies published in the <em>Veterinary Surgery</em> journal and the <em>Journal of Small Animal Practice</em> demonstrate that pets receiving structured rehabilitation programmes after orthopaedic surgery recover faster, develop better muscle mass, achieve greater joint range of motion, and return to normal activity sooner compared to rest alone.</p>
        <ul className="space-y-2 pl-5 list-disc" data-aos="fade-up">
          <li className="leading-relaxed">Dogs recovering from orthopaedic surgery (TPLO, TTA, fracture repair)</li>
          <li className="leading-relaxed">Dogs diagnosed with IVDD (intervertebral disc disease)</li>
          <li className="leading-relaxed">Animals with neurological conditions (DM, FCE, vestibular)</li>
          <li className="leading-relaxed">Overweight pets needing safe exercise</li>
          <li className="leading-relaxed">Pets with arthritis or degenerative joint disease</li>
          <li className="leading-relaxed">Pets with hip or elbow dysplasia</li>
          <li className="leading-relaxed">Senior pets with declining mobility</li>
          <li className="leading-relaxed">Cats recovering from injury or surgery</li>
        </ul>
        <h2 className="text-2xl font-bold mt-10 mb-4" data-aos="fade-up">Our Rehabilitation Services</h2>
        <p className="leading-relaxed mb-4" data-aos="fade-up">A comprehensive toolkit — not just one treatment</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Underwater treadmill and warm water therapy for low-impact exercise, muscle building, and pain-free movement. Ideal for post-surgical recovery, arthritis, and weight management.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Manual therapy, therapeutic exercises, balance training, and gait retraining. Builds strength, restores range of motion, and retrains movement patterns after injury or surgery.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Veterinary acupuncture and Traditional Chinese Veterinary Medicine (TCVM) for pain management, inflammation reduction, and support of natural healing processes.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Deep tissue photobiomodulation using Class 4 therapeutic laser. Stimulates cellular repair, reduces inflammation, and provides analgesia at the tissue level. Non-invasive and painless — most pets relax during treatment. Effective for acute injuries, chronic pain, and wound healing.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Electrical currents stimulate muscle contractions in weakened or atrophied muscles. NMES is essential for neurological patients who cannot voluntarily activate muscles, and for maintaining muscle mass in post-surgical patients during restricted activity periods.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">HBOT delivers 100% oxygen at increased atmospheric pressure, accelerating wound healing, reducing inflammation, and supporting recovery from neurological conditions.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Additional modalities available: therapeutic ultrasound, shockwave therapy (ESWT), TCVM Tui-Na, thermotherapy &amp; cryotherapy, and proprioception exercises.</p>
        <h2 className="text-2xl font-bold mt-10 mb-4" data-aos="fade-up">Why Choose RehabVet for Animal Rehabilitation?</h2>
        <p className="leading-relaxed mb-4" data-aos="fade-up">RehabVet was established as Singapore&apos;s first full-service veterinary rehabilitation centre. Every therapist, piece of equipment, and treatment room is purpose-built for rehabilitation — we are not a general practice clinic that offers rehab on the side.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">We combine hydrotherapy, physiotherapy, acupuncture, laser therapy, electrotherapy, and hyperbaric oxygen into comprehensive programmes. Research consistently shows that multimodal rehabilitation delivers superior outcomes compared to any single modality alone.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">All rehabilitation sessions are designed and supervised by our veterinary team, led by Dr. Sara Lam BVSc. Our therapists hold internationally recognised rehabilitation qualifications and work under direct veterinary oversight.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">We measure muscle circumference, joint range of motion, gait quality, and functional mobility at regular reassessments. You see your pet&apos;s improvement in concrete numbers — not just &quot;they seem better.&quot;</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">We have extensive experience treating feline patients. Our therapists adapt techniques for cats&apos; unique physiology and temperament — because cats deserve expert rehabilitation too.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Every pet receives individual attention for their entire session. No group classes, no distractions — just focused, expert care tailored to your pet&apos;s specific needs and goals.</p>
        <h2 className="text-2xl font-bold mt-10 mb-4" data-aos="fade-up">10 Benefits of Animal Rehabilitation</h2>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Veterinary research consistently shows that structured post-operative rehabilitation can reduce recovery times by 30–50%. Dogs undergoing rehabilitation after cruciate ligament repair return to full weight-bearing significantly earlier than without.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Rehabilitation provides natural, drug-free pain relief through acupuncture, therapeutic laser, TENS, and manual therapy — reducing dependence on pain medications and their long-term side effects.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Through targeted stretching, strengthening exercises, and hydrotherapy, rehabilitation restores joint range of motion and builds supporting muscle mass — especially important for osteoarthritis, hip dysplasia, and IVDD.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Our programmes incorporate controlled exercise regimens — including underwater treadmill sessions — that help overweight pets shed excess kilograms safely, reducing stress on joints and improving cardiovascular health.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Pets recovering from spinal injuries, strokes, or neurological conditions benefit from targeted neuromuscular rehabilitation. Exercises retrain proprioception and stimulate nerve pathways to restore function.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Regular rehabilitation sessions help maintain mobility, preserve independence, and manage chronic pain — allowing senior dogs and cats to remain active and comfortable in their golden years.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Pets in chronic pain often become withdrawn, anxious, or irritable. By effectively managing pain and restoring mobility, rehabilitation frequently leads to noticeable improvements in mood, energy levels, and overall behaviour.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">When an animal favours one limb, the opposite limb and spine bear extra load — leading to secondary injuries over time. Rehabilitation addresses the original condition while correcting compensatory movement patterns.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Every rehabilitation programme includes regular reassessments — muscle circumference measurements, gait analysis, joint range of motion testing, and functional mobility scoring — so you can see improvement in verifiable terms.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">In some cases, structured rehabilitation can successfully manage conditions conservatively — including mild cruciate ligament injuries, early-stage arthritis, and certain soft tissue injuries — potentially avoiding or delaying surgery.</p>
        <h3 className="text-xl font-bold mt-8 mb-4" data-aos="fade-up">Conditions We Treat with Animal Rehabilitation</h3>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Pets recovering from orthopaedic surgery (TPLO, TTA, fracture repair, FHO) or spinal surgery benefit from early, structured rehabilitation. We begin gentle treatment within days of surgery and progress systematically as healing allows — reducing recovery time by 30–50% compared to rest alone.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Arthritis is the single most common reason pets are referred for rehabilitation. Our multimodal approach — combining hydrotherapy, physiotherapy, laser therapy, and acupuncture — reduces pain, builds protective muscle mass, and slows disease progression.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">IVDD patients — particularly Dachshunds, French Bulldogs, Corgis, and Shih Tzus — often present with hind limb weakness, ataxia, or paralysis. Our rehabilitation programmes combine neuromuscular re-education, hydrotherapy, laser therapy, and proprioceptive exercises to promote nerve recovery.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Dysplastic joints cause lifelong pain and progressive degeneration. Rehabilitation strengthens the muscles surrounding affected joints, improves stability, and reduces pain — often delaying or avoiding surgical intervention.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Degenerative myelopathy, fibrocartilaginous embolism (FCE), vestibular disease, and other neurological conditions respond well to targeted rehabilitation. Balance exercises, assisted standing, hydrotherapy, and controlled movement help retrain neural pathways and maximise remaining function.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Both pre-surgical &quot;prehabilitation&quot; and post-surgical rehabilitation are critical for cruciate cases. Pre-surgical physical therapy builds muscle mass and maintains fitness before surgery. Post-surgical therapy restores range of motion, rebuilds quadriceps and hamstring strength, and retrains normal weight-bearing gait patterns.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Overweight pets face significantly higher risks of joint disease, diabetes, and reduced life expectancy. Our underwater treadmill provides high-calorie-burn, low-impact exercise — safe even for pets who cannot tolerate conventional exercise due to pain or mobility limitations.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Older dogs and cats naturally lose muscle mass, joint flexibility, and balance. Regular rehabilitation sessions maintain mobility, prevent falls, manage age-related pain, and preserve quality of life — helping senior pets stay active and independent.</p>
        <h3 className="text-xl font-bold mt-8 mb-4" data-aos="fade-up">How Animal Rehabilitation Works at RehabVet</h3>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Your pet&apos;s first visit includes a comprehensive assessment: medical history review, gait and posture observation, joint range of motion and muscle circumference measurements, pain assessment, and functional mobility testing. We review any imaging (X-rays, MRI, CT) and surgical reports.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Based on the assessment, our veterinary team designs a tailored rehabilitation programme with specific goals, selected modalities, recommended frequency, and expected timelines. We discuss everything with you — including costs — before beginning treatment.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Each session combines multiple modalities selected for your pet: manual therapy, therapeutic exercises, hydrotherapy, laser therapy, acupuncture, or electrotherapy. Our therapists adjust the programme in real time based on your pet&apos;s response.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Progress is measured objectively at regular intervals — muscle circumference, joint angles, gait scores, and functional mobility. We adjust the programme based on data, not guesswork. You receive clear updates on your pet&apos;s progress at every reassessment.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Between clinic sessions, we provide specific exercises for you to practise at home. These are carefully demonstrated and selected to complement your pet&apos;s in-clinic treatment — significantly improving outcomes by providing daily therapeutic activity.</p>
        <h3 className="text-xl font-bold mt-8 mb-4" data-aos="fade-up">What to Expect at Your Pet&apos;s First Rehabilitation Session</h3>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Bring your pet&apos;s medical history, any imaging reports (X-rays, MRI, CT), surgical reports, and a list of current medications. If your pet has had recent surgery, bring the surgical discharge notes.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Your first visit is longer because it includes a full assessment. Our veterinary team will observe your pet&apos;s gait and posture, perform a physical examination, measure joint range of motion and muscle mass, and discuss your goals. Treatment begins at this first visit if appropriate. You are welcome to stay, observe, and ask questions throughout.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Some pets are tired after their first sessions — this is normal and indicates the muscles have been working. Your therapist will explain the recommended treatment plan, frequency, and expected timeline. Home exercises will be demonstrated for you to practise between visits. Most pets show visible improvement within 3–4 sessions.</p>
        <h3 className="text-xl font-bold mt-8 mb-4" data-aos="fade-up">Animal Rehabilitation Pricing in Singapore</h3>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Rehabilitation pricing at RehabVet depends on the modalities required and your pet’s treatment plan. All costs are discussed transparently at your initial consultation.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Many pet insurance policies in Singapore now cover rehabilitation therapies. We recommend checking with your insurer before your first appointment. We provide itemised invoices for insurance claims.</p>
        <p className="leading-relaxed mb-4" data-aos="fade-up">Pricing varies based on session duration and additional modalities (laser therapy, shockwave, acupuncture, HBOT). Your veterinary team will discuss all costs before beginning treatment.</p>
        <h3 className="text-xl font-bold mt-8 mb-4" data-aos="fade-up">Meet Your Rehabilitation Team</h3>
        <h3 className="text-xl font-bold mt-8 mb-4" data-aos="fade-up">Rehabilitation Success Stories</h3>
        <h2 className="text-2xl font-bold mt-12 mb-6" data-aos="fade-up">Frequently Asked Questions About Animal Rehabilitation</h2>
        <div className="space-y-3" data-aos="fade-up">
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">What is animal rehabilitation?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Animal rehabilitation (also called veterinary rehabilitation or pet physical therapy) is the use of evidence-based physical therapies to restore movement, reduce pain, and improve function in animals. It encompasses multiple modalities — hydrotherapy, physiotherapy, acupuncture, laser therapy, electrotherapy, and more — combined into a structured treatment programme tailored to each patient. At RehabVet, every programme is designed and supervised by our veterinary team.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">How much does animal rehabilitation cost in Singapore?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">At RehabVet, initial rehabilitation consultations are –, which includes a comprehensive assessment and your first treatment session. Follow-up sessions range from – depending on the modalities used. Package rates are available for ongoing treatment plans. Many pet insurance policies in Singapore now cover rehabilitation.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">What does a rehabilitation session involve?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Each session begins with an assessment of your pet’s current condition — gait, posture, pain levels, and progress since the last visit. Treatment then combines multiple modalities: manual therapy, therapeutic exercises, hydrotherapy, laser, electrotherapy, or acupuncture. Sessions typically last 30–60 minutes, adjusted in real time based on your pet’s response.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">How long does an animal rehabilitation programme take?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Animal rehabilitation (also called veterinary rehabilitation or pet physical therapy) is the use of evidence-based physical therapies to restore movement, reduce pain, and improve function in animals. It encompasses multiple modalities — hydrotherapy, physiotherapy, acupuncture, laser therapy, electrotherapy, and more — combined into a structured treatment programme tailored to each patient’s condition and goals. At RehabVet, every programme is designed and supervised by our veterinary team.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">What conditions benefit from animal rehabilitation?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">At RehabVet, initial rehabilitation consultations are $150–$200, which includes a comprehensive assessment and your first treatment session. Follow-up sessions range from $100–$160 depending on the modalities used. Package rates are available for ongoing treatment plans. Many pet insurance policies in Singapore now cover rehabilitation — we recommend checking with your insurer before your first appointment.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">What are the healing effects of hydrotherapy?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Each session begins with an assessment of your pet’s current condition — gait, posture, pain levels, and progress since the last visit. Treatment then combines multiple modalities selected for your pet’s specific needs: manual therapy, therapeutic exercises, hydrotherapy, laser, electrotherapy, or acupuncture. Sessions typically last 30–60 minutes. Your therapist adjusts the programme in real time based on your pet’s response.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">Can cats benefit from rehabilitation?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Can cats benefit from rehabilitation? Yes. While dogs make up the majority of rehabilitation patients, cats benefit significantly from rehabilitation too — particularly for arthritis management, post-surgical recovery, and neurological conditions. Our therapists are experienced with feline patients and adapt techniques to suit cats’ unique temperament and physiology. Hydrotherapy is less commonly used for cats, but land-based physiotherapy, laser therapy, and acupuncture are highly effective.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">How often should my pet go for rehabilitation?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Frequency depends on your pet’s condition and treatment phase. For post-surgical rehabilitation, we typically recommend 2–3 sessions per week initially, reducing to once weekly as recovery progresses. Chronic conditions like arthritis often benefit from 1–2 sessions per week, transitioning to weekly or fortnightly maintenance.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">Does pet insurance cover rehabilitation in Singapore?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">The most common conditions we treat include: post-surgical recovery (TPLO, TTA, fracture repair, spinal surgery), osteoarthritis, IVDD, hip and elbow dysplasia, neurological conditions (degenerative myelopathy, FCE, vestibular disease), cruciate ligament injuries, soft tissue injuries, obesity, and geriatric mobility decline. Both dogs and cats benefit from rehabilitation.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">What is the success rate of hydrotherapy?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Physiotherapy is one component of rehabilitation. Veterinary rehabilitation is the broader umbrella term encompassing all physical therapies — including physiotherapy, hydrotherapy, acupuncture, laser therapy, electrotherapy, shockwave therapy, and more. At RehabVet, most patients receive a multimodal programme combining several modalities for optimal results.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">Is hydrotherapy good for old dogs?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">Rehabilitation is one of the most beneficial interventions for senior pets. Older dogs and cats commonly suffer from muscle loss, arthritis, reduced balance, and declining mobility. Our programmes are adapted to each senior pet’s abilities and tolerance — gentle, progressive, and always respectful of their limitations.</div>
            </details>
            <details className="group rounded-xl border border-gray-200 bg-white">
              <summary className="flex cursor-pointer items-center justify-between p-5 font-medium text-dark">Does hydrotherapy help dogs with arthritis?</summary>
              <div className="px-5 pb-5 leading-relaxed border-t border-gray-200 pt-4 text-gray-700">This depends on the surgery type and your surgeon’s recommendations. Gentle manual therapy and passive range-of-motion exercises can often begin within 3–7 days post-surgery. We always coordinate with your primary vet or surgeon to ensure timing is appropriate and safe.</div>
            </details>
        </div>

        <div className="mt-10 rounded-2xl bg-primary_shade p-8 text-center" data-aos="fade-up">
          <h3 className="text-xl font-bold">Ready to Get Started?</h3>
          <p className="mt-2">Contact us on WhatsApp to book your pet&apos;s first session.</p>
          <div className="mt-4">
            <a href="https://wa.me/6587987554" className="inline-block rounded-full bg-primary px-6 py-3 text-white font-medium hover:opacity-90 transition">WhatsApp Us</a>
          </div>
        </div>
    </>
  )
}
